In [55]:
from PIL import Image
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [47]:

import numpy as np # linear algebras

paths_img = []

import os
for dirname, _, filenames in os.walk('case3-datasaur-photo/techosmotr/techosmotr/train'):
    for filename in filenames:
        paths_img.append(os.path.join(dirname, filename))


In [3]:
shapes = []

for i in paths_img:
    img = Image.open(i)
    shapes.append(np.array(img).shape)

In [4]:
shapes

[(480, 640, 3),
 (600, 800, 3),
 (480, 640, 3),
 (600, 800, 3),
 (720, 960, 3),
 (600, 800, 3),
 (600, 800, 3),
 (480, 640, 3),
 (480, 640, 3),
 (600, 800, 3),
 (480, 640, 3),
 (600, 800, 3),
 (600, 800, 3),
 (480, 640, 3),
 (480, 640, 3),
 (720, 960, 3),
 (480, 640, 3),
 (480, 640, 3),
 (480, 640, 3),
 (600, 800, 3),
 (600, 800, 3),
 (480, 640, 3),
 (720, 960, 3),
 (600, 750, 3),
 (480, 640, 3),
 (480, 640, 3),
 (600, 800, 3),
 (600, 800, 3),
 (720, 960, 3),
 (480, 640, 3),
 (480, 640, 3),
 (600, 800, 3),
 (480, 640, 3),
 (720, 960, 3),
 (480, 640, 3),
 (480, 640, 3),
 (480, 640, 3),
 (480, 640, 3),
 (480, 640, 3),
 (480, 640, 3),
 (480, 640, 3),
 (480, 640, 3),
 (600, 800, 3),
 (720, 960, 3),
 (600, 800, 3),
 (480, 640, 3),
 (480, 640, 3),
 (480, 640, 3),
 (480, 640, 3),
 (720, 960, 3),
 (720, 960, 3),
 (600, 733, 3),
 (600, 800, 3),
 (480, 640, 3),
 (480, 640, 3),
 (720, 960, 3),
 (720, 960, 3),
 (480, 640, 3),
 (480, 640, 3),
 (720, 960, 3),
 (720, 960, 3),
 (600, 800, 3),
 (600, 8

In [17]:
shapes = np.array(shapes)

In [24]:
X, Y = [], []
for i in shapes:
    print(i)
    x, y = i[0], i[1]
    X.append(x)
    Y.append(y)

X = np.array(X)
Y = np.array(Y)

[480 640   3]
[600 800   3]
[480 640   3]
[600 800   3]
[720 960   3]
[600 800   3]
[600 800   3]
[480 640   3]
[480 640   3]
[600 800   3]
[480 640   3]
[600 800   3]
[600 800   3]
[480 640   3]
[480 640   3]
[720 960   3]
[480 640   3]
[480 640   3]
[480 640   3]
[600 800   3]
[600 800   3]
[480 640   3]
[720 960   3]
[600 750   3]
[480 640   3]
[480 640   3]
[600 800   3]
[600 800   3]
[720 960   3]
[480 640   3]
[480 640   3]
[600 800   3]
[480 640   3]
[720 960   3]
[480 640   3]
[480 640   3]
[480 640   3]
[480 640   3]
[480 640   3]
[480 640   3]
[480 640   3]
[480 640   3]
[600 800   3]
[720 960   3]
[600 800   3]
[480 640   3]
[480 640   3]
[480 640   3]
[480 640   3]
[720 960   3]
[720 960   3]
[600 733   3]
[600 800   3]
[480 640   3]
[480 640   3]
[720 960   3]
[720 960   3]
[480 640   3]
[480 640   3]
[720 960   3]
[720 960   3]
[600 800   3]
[600 800   3]
[600 800   3]
[480 640   3]
[720 960   3]
[480 640   3]
[600 750   3]
[480 640   3]
[480 640   3]
[480 640   3]
[480 6

In [42]:
def median(X):
    X.sort() 
    mid = len(X) // 2
    res = (X[mid] + X[~mid]) / 2
    return res

In [43]:
print(X.min(), Y.min())
print(X.mean(), Y.mean())
print(median(X), median(Y))

240 320
664.4502657555049 1007.2566438876233
720.0 960.0


here i decided that i will resize all images to (300,400,3)

In [51]:
ds = tf.keras.utils.image_dataset_from_directory(
    directory= 'case3-datasaur-photo/techosmotr/techosmotr/train/fictivniye(fictitious)',
    labels=None,
    label_mode=None,
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(400, 500),  # just preserve image accuracy during augmentation (it will be resized into 300x400 during training)
    shuffle=None,
    seed=111,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=True)

Found 2062 files belonging to 1 classes.


## Data Augmentation for fictivniye(fictitious) to balance dataset

In [73]:
import os

paths = []

for dirname, _, filenames in os.walk('case3-datasaur-photo/techosmotr/techosmotr/train/fictivniye(fictitious)'):
    for filename in filenames:
        paths.append(os.path.join(dirname, filename))

In [72]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img


datagen = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.1,
        height_shift_range=0.1,
        shear_range=0.1,
        zoom_range=0.1,
        horizontal_flip=False,
        fill_mode='nearest')


for i in paths:
    img = (np.array(tf.keras.utils.load_img(
        i,
        grayscale=False,
        color_mode='rgb',
        target_size=(400, 500),
        interpolation='bilinear',
        keep_aspect_ratio=False))/255).reshape(-1, 400,500,3)
    
    j=1

    for batch in datagen.flow(img, batch_size=1,
                          save_to_dir='augmented images', save_prefix='t', save_format='jpeg'):

        break  # otherwise the generator would loop indefinitely

I created about 4 000 new images and deleted some portion of it before i merged it with fictivniye